apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-name-master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-name-master
  template:
    metadata:
      labels:
        app: project-name-master
    spec:
      containers:
        - image: '{client_aws_url}/project-name:{commit_id_image_tag}'
          name: back-end
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: '{secret_manager_name}'
