apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-name-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-name-master
  template:
    metadata:
      labels:
        app: project-name-master
    spec:
      containers:
      - name: back-end
        image: {client_aws_url}/project-name:{commit_id_image_tag}
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
          name: {secret_manager_name}
